// GENERATED by packages/backend/scripts/plans-sync.ts from packages/backend/src/modules/billing/plans.ts. Do not edit.
import type { FeatureKey, PlanDef } from '@/types/billing';

export const PLANS: PlanDef[] = [
  {
    "key": "FREE",
    "name": "Free",
    "summary": "Core HR, leave and attendance for small teams.",
    "pricePaise": {
      "MONTHLY": 0,
      "ANNUAL": 0
    },
    "maxEmployees": 20,
    "minSeats": 0,
    "features": [
      "core",
      "leave",
      "attendance",
      "selfService",
      "privacy"
    ],
    "highlights": [
      "Up to 20 employees",
      "Leave and attendance",
      "Web and mobile self-service",
      "DPDP privacy tools"
    ]
  },
  {
    "key": "STANDARD",
    "name": "Standard",
    "summary": "Payroll and statutory compliance, done every month.",
    "pricePaise": {
      "MONTHLY": 5900,
      "ANNUAL": 4900
    },
    "maxEmployees": null,
    "minSeats": 10,
    "features": [
      "core",
      "leave",
      "attendance",
      "selfService",
      "privacy",
      "payroll",
      "statutory",
      "lifecycle",
      "expenses",
      "helpdesk"
    ],
    "highlights": [
      "Everything in Free",
      "Payroll with PF, ESI, PT, LWF and TDS",
      "ECR, returns and compliance calendar",
      "Onboarding, exits and F&F",
      "Expenses and helpdesk"
    ]
  },
  {
    "key": "PROFESSIONAL",
    "name": "Professional",
    "summary": "The full suite for growing companies.",
    "pricePaise": {
      "MONTHLY": 11900,
      "ANNUAL": 9900
    },
    "maxEmployees": null,
    "minSeats": 10,
    "features": [
      "core",
      "leave",
      "attendance",
      "selfService",
      "privacy",
      "payroll",
      "statutory",
      "lifecycle",
      "expenses",
      "helpdesk",
      "performance",
      "recruitment",
      "analytics",
      "aiAssistant",
      "biometric",
      "googleSignIn"
    ],
    "highlights": [
      "Everything in Standard",
      "Performance and appraisals",
      "Recruitment and careers page",
      "Analytics and custom reports",
      "AI policy answers, biometric devices, Google sign-in"
    ]
  },
  {
    "key": "ENTERPRISE",
    "name": "Enterprise",
    "summary": "Dedicated database, SLA and assisted rollout.",
    "pricePaise": null,
    "maxEmployees": null,
    "minSeats": 250,
    "features": [
      "core",
      "leave",
      "attendance",
      "selfService",
      "privacy",
      "payroll",
      "statutory",
      "lifecycle",
      "expenses",
      "helpdesk",
      "performance",
      "recruitment",
      "analytics",
      "aiAssistant",
      "biometric",
      "googleSignIn"
    ],
    "highlights": [
      "Everything in Professional",
      "Dedicated Supabase project in India",
      "99.9% uptime SLA",
      "Assisted payroll migration"
    ]
  }
];

export const FEATURE_LABELS: Record<FeatureKey, string> = {
  "core": "Employees, org chart, documents, policies, announcements",
  "leave": "Leave policies, accrual, encashment, comp-off",
  "attendance": "Web & mobile check-in, geo-fence, selfie, shifts",
  "selfService": "Employee self-service on web and mobile",
  "privacy": "DPDP privacy tools: consent, data export, erasure, breach register",
  "payroll": "Payroll with PF, ESI, PT, LWF, TDS and payslips",
  "statutory": "ECR, ESI, PT, Form 24Q / 143, bank advice, compliance calendar",
  "lifecycle": "Onboarding, exits and full & final settlement",
  "expenses": "Expense claims, travel requests and reimbursements",
  "helpdesk": "HR helpdesk tickets",
  "performance": "Goals, appraisal cycles and salary revisions",
  "recruitment": "Job openings, careers page, interviews and offers",
  "analytics": "MIS reports, custom report builder, attrition and anomaly insights",
  "aiAssistant": "Policy answers written by an AI model",
  "biometric": "Biometric device integration",
  "googleSignIn": "Sign in with Google (Supabase Auth)"
};

export const TRIAL_DAYS = 14;
