/**
 * Writes the plan catalogue to the web app so the public pricing page renders statically from the same source as the
 * API. Run after editing src/modules/billing/plans.ts:  pnpm --filter jantahr-backend plans:sync
 * A unit test (plans-sync.spec.ts) fails when the generated file is stale.
 */
import * as fs from 'fs';
import * as path from 'path';
import { FEATURES, PLANS, TRIAL_DAYS } from '../src/modules/billing/plans';

export const GENERATED_PATH = path.resolve(__dirname, '../../frontend/src/lib/plans/plans.generated.ts');

export function render(): string {
  return `// GENERATED by packages/backend/scripts/plans-sync.ts from packages/backend/src/modules/billing/plans.ts. Do not edit.
import type { FeatureKey, PlanDef } from '@/types/billing';

export const PLANS: PlanDef[] = ${JSON.stringify(Object.values(PLANS), null, 2)};

export const FEATURE_LABELS: Record<FeatureKey, string> = ${JSON.stringify(FEATURES, null, 2)};

export const TRIAL_DAYS = ${TRIAL_DAYS};
`;
}

if (require.main === module) {
  fs.writeFileSync(GENERATED_PATH, render());
  console.log(`wrote ${path.relative(process.cwd(), GENERATED_PATH)}`);
}
